angular.module('exzotron')
  .factory('IncomeService', ['$resource', 'API', function ($resource, API) {
    return $resource(API.income, {}, {
      'get': {method: 'GET', isArray: true},
      'tankIncomeLog': {method: 'GET', isArray: true, url: API.tankIncomeLog, params: {id: '@id'}},
      'getOne': {method: 'GET', isArray: false, url: API.income + '/:id'},
      'add': {method: 'POST', isArray: false},
      'save': {method: 'PUT', isArray: false},
      'setTankLog': {method: 'PUT', isArray: false, url: API.setTankLog},
      'delete': {method: 'DELETE', isArray: false, params: {id: '@id'}},
      'changeStatus': {method: 'PATCH', isArray: false, params: {id: '@id', status: '@status'}},
      'autogenerated': {
        method: 'PATCH',
        url: API.income + '/auto',
        isArray: false,
        params: {id: '@id', autogenerated: '@autogenerated'}
      },
      'generate': {method: 'GET', url: API.income + '/generate', isArray: false},
      'getInvoiseOperationTypes': {method: 'GET', url: API.income + '/invoise_operation_types', isArray: true},
    });
  }]);
