(function () {
  'use strict';

  angular
    .module('exzotron', [
      'app.route',
      'app.config',
      'ngResource',
      'ui.bootstrap',
      'ngSanitize',
      'tableSort',
      'toaster',
      'rzTable',
      'ngCookies',
      'angularSpinner',
      'pascalprecht.translate',
      'ngFileUpload',
      'chart.js',
      'ui.mask',
      'checklist-model',
      'shagstrom.angular-split-pane',
      'fixed.table.header',
      'ui.bootstrap.datetimepicker',
      'ui.select',
      'angular-loading-bar'])
    .config(['usSpinnerConfigProvider', '$translateProvider', 'ChartJsProvider', 'uibDatepickerPopupConfig', function (usSpinnerConfigProvider, $translateProvider, ChartJsProvider, uibDatepickerPopupConfig) {
      usSpinnerConfigProvider.setDefaults({
        lines: 10, // The number of lines to draw
        length: 10, // The length of each line
        width: 3, // The line thickness
        radius: 10, // The radius of the inner circle
        scale: 0.35, // Scales overall size of the spinner
        corners: 1, // Corner roundness (0..1)
        speed: 1.5, // Rounds per second
        rotate: 0, // The rotation offset
        direction: 1, // 1: clockwise, -1: counterclockwise
        color: '#ffffff', // CSS color or array of colors
        fadeColor: 'transparent', // CSS color or array of colors
        top: '50%', // Top position relative to parent
        left: '50%', // Left position relative to parent
        shadow: '0 0 1px transparent', // Box-shadow for the lines
        zIndex: 2000000000, // The z-index (defaults to 2e9)
        className: 'spinner' // The CSS class to assign to the spinner
      });

      uibDatepickerPopupConfig.closeText = 'Закрыть';
      uibDatepickerPopupConfig.currentText = 'Сегодня';
      uibDatepickerPopupConfig.clearText = 'Очистить';

      $translateProvider.translations('ru', {
        'ROUTER_IP': 'IP роутера',
        'PARKTRONIK_CENTER_POLL_INTERVAL_MS': 'Интервал опроса центр. парктроника (мс)',
        'PARKTRONIK_CENTER_POLL_COUNT': 'Количество попыток опроса центр. парктроника',
        'TABLO_POLL_INTERVAL_MS': 'Интервал опроса табло (мс)',
        'TABLO_POLL_COUNT': 'Количество попыток опроса табло',
        'IS_ONLINE': 'Онлайн статус',
        'LAST_SEEN': 'Последняя активность',
        'RESPONSIBLE': 'Ответственный',
        'COMBINE': 'Объединить',
        'SEND': 'Отправить',
        'ENTER_MESSAGE': 'Введите сообщение',
        'USER_LIST': 'Список пользователей',
        'MINIMUM_BALANCE': 'Минимальный баланс',
        'STOP_BALANCE': 'Баланс блокировки',
        'ACCOUNT': 'Счет',
        'RECALCULATE': 'Пересчитать',
        'DATE': 'Дата',
        'UPLOAD_PHOTO': 'Загрузить фото',
        'PRODUCT': 'Продукт',
        'DEBIT': 'Начислено',
        'CREDIT': 'Выдано',
        'COUNT': 'Количество',
        'OBJECT': 'Узел',
        'MACHINE_RFID': 'RFID Машины',
        'OBJECT_RFID': 'RFID Объекта',
        'TOTAL_SUM': 'Общая сумма',
        'SUM': 'Сумма',
        'NO_DATA': 'Нет Данных',
        'NAME': 'Имя',
        'CAMERA_NAME': 'Имя камеры',
        'LAST_PROCESSING_DATE': 'Дата последней обработки',
        'PHOTO_PROCESSING_ENABLED': 'Обработка фото',
        'VIDEO_PROCESSING_ENABLED': 'Обработка видео',
        'STORAGE_HOURS': 'Время хранения (ч.)',
        'INVOISE_OPERATION_TYPE': 'Тип поступления',
        'ACTIVE': 'Активно',
        'FILTERS': 'Фильтры',
        'SHOW_BLOCKED_CARDS': 'Показывать заблокированные карты',
        'TELEGRAM': 'Телеграм',
        'CREATED_BY' : 'Кем создано',
        'DECREASE' : 'Убыль',
        'TRK_TYPE' : 'Тип ТРК',
        'LICENSE_DATE' : 'Дата лицензии',
        'EXPIRED' : 'Просрочено (дни)',
        'REGISTRATION_DATE': 'Дата регистрации',
        'OBJECTS_COUNT': 'Количество Объектов',
        'MAXIMUM_OBJECTS': 'Максимум Объектов',
        'OWNER': 'Владелец',
        'PHONE': 'Телефон',
        'STATUS': 'Статус',
        'BALANCE': 'Баланс',
        'DAY_LIMIT': 'Дневной Лимит',
        'LIMIT_REMAINS': 'Лимит',
        'LIMIT_REMAINS_TYPE': 'Период',
        'DAY_BALANCE': 'Остаток',
        'TOTALS': 'Итого',
        'FREE': 'Свободно',
        'GROUP_BY_OBJECTS': 'По Узлам',
        'WITH_MOVES': 'С Движениями',
        'PRICE': 'Цена',
        'SEARCH': 'Поиск',
        'CURRENT_FUEL_TYPE': 'Текущий Вид Топлива',
        'GROUP_BY_OBJECTS_TOOLTIP': 'Группировать по узлам',
        'ONLY_WITH_MOVES_TOOLTIP': 'Только с движениями по картам',
        'LOCK': 'Заблокировать',
        'UNLOCK': 'Разблокировать',
        'LAST_RECEIVED_PACKAGE_TIME': 'Последний пакет получен',
        'NOT_SENT_MESSAGES_COUNT': 'Неотправленных сообщений',
        'LIMIT_TYPE': 'Тип RFID',
        'LIMIT_CARD': 'Лимитная карта',
        'UNLIMITED_CARD': 'Безлимитная карта',
        'TYPE': 'Тип',
        'UNITS': 'Единицы измерения',
        'SOURCE': 'Источник',
        'CALIBRATION': 'Тарировка',
        'INPUT': 'Входное значение',
        'CALIBRATION_VALUE': 'Тарировочное значение',
        'ADDRESS': 'Адрес',
        'STOREHOUSE': 'Хранилище',
        'RELATED_STOREHOUSE': 'Связанное хранилище',
        'DIVISION': 'Подразделение',
        'LICENSE_PLATE': 'Гос. номер',
        'TRAILER_PLATE': 'Гос. номер прицепа',
        'CARGO': 'Груз',
        'BRAND': 'Бренд',
        'DOCUMENT': 'Документ',
        'GARAGE_NUMBER': 'Номер гаража',
        'VOLUME': 'Объем',
        'DEALER': 'Дилер',
        'LICENCE': 'Лицензия',
        'SIZE': 'Размер',
        'IMPORT': 'Импорт',
        'EXPORT': 'Экспорт',
        'LEVEL': 'Уровень (л)',
        'LEVEL_END': 'Факт. Уровень',
        'LEVEL_REMAINS': 'Нач. остаток',
        'LEVEL_START': 'Нач. Ост.',
        'LEVEL_FINAL': 'Кон. остаток',
        'TEMPERATURE': 'Температура ('+'\u2103' + ')',
        'DENSITY': 'Плотность (кг/м³)',
        'WEIGHT': 'Вес (кг)',
        'WATER': 'Вода',
        'LEVEL_CM': 'Уровень (см)',
        'CHARTS': 'Графики',
        'CONSUMPTION': 'Расход',
        'INVENTORY': 'Инвентаризация',
        'INTERNAL_DEBIT': '(Вн.) приход',
        'INTERNAL_CREDIT': '(Вн.) расход',
        'VEHICLE_CONSUMPTION': 'Расход на технику',
        'DISTRIBUTOR': 'Приход от поставщика',
        'BY_REMAINS': 'По остатку',
        'BY_REMAINS_DETAILED': 'По остатку (детальный)',
        'BY_DAYS': 'По дням',
        'CONTROL': 'Контроль',
        'INCOME': 'Приход',
        'DELIVERY_SUM': 'Сумма доставки',
        'FINAL_COUNTER': 'Кон. Ост.',
        'DEVIATION': 'Отклонение',
        'INTERNAL_INCOME': 'Вн. приход',
        'INTERNAL_CONSUMPTION': 'Вн. расход',
        'ITN': 'ИНН',
        'RECIPIENT': 'Получатель',
        'SENDER': 'Отправитель',
        'SUPPLIER': 'Поставщик',
        'TANK': 'Емкость',
        'TEMPERATURE_DOC': 'Температура при отгрузке',
        'TEMPERATURE_IN': 'Температура при приеме',
        'TEMPERATURE_DEVIATION': 'Отклонение температуры',
        'DENSITY_DOC': 'Плотность при отгрузке',
        'DENSITY_IN': 'Плотность при приеме',
        'DENSITY_DEVIATION': 'Отклонение плотности',
        'LITRES_COUNTER_DOC': 'Литры при отгрузке',
        'LITRES_COUNTER_IN': 'Литры при приеме',
        'LITRES_COUNTER_DEVIATION': 'Отклонение литров',
        'LITRES_DENSITY_DOC': 'Литры при отгрузке по плотности',
        'LITRES_DENSITY_IN': 'Литры при приеме по плотности',
        'LITRES_DENSITY_DEVIATION': 'Отклонение литров по плотности',
        'WEIGHT_DOC': 'Масса при отгрузке',
        'WEIGHT_IN': 'Масса при приеме',
        'WEIGHT_DEVIATION': 'Отклонение массы',
        'COMMENT': 'Комментарий',
        'PRODUCT_NAME_DOC': 'Наименование продукта по ТТН',
        'DOC_NUM': 'Номер ТТН',
        'DOC_DATE': 'Дата ТТН',
        'USER': 'Пользователь',
        'CREATED_AT': 'Создано',
        'UPDATED_AT': 'Обновлено',
        'RUN_DATE': 'Дата запуска',
        'RUN_TIME': 'Время запуска',
        'PERIOD': 'Период',
        'PIN_CODE': 'ПИН',
        'EMPLOYEE': 'Сотрудник',
        'DATE_FROM': 'С',
        'DATE_TO': 'По',
        'SELECT_ALL': 'Выделить все',
        'ALL': 'Все',
        'OFFSET': 'Смещение',
        'CORRECTION': 'Коррекция',
        'DESCRIPTION': 'Описание',
        'LOCATION': 'Локация',
        'ROUTER_IMEI': 'IMEI роутера',
        'CONTROLLER_IP': 'IP контроллера',
        'REPORT_BY_RFID': "Отчет по карте {{item}} {{item2}}",
        'REPORT_TOTALS_BY_RFID': "Итоги по картам",
        'REPORT_TOTALS_BY_VEHICLE': "Итоги по автомобилям",
        'REPORT_DETAILED_BY_RFID': "Детальный отчет по картам",
        'REPORT_BY_DIVISION': 'Отчет по подразделению {{item}}',
        'REPORT_FUEL_MOVING': 'Отчет движения топлива',
        'REPORT_FUEL_MOVING_STOREHOUSE': 'Отчет движения топлива по складу {{item}}',
        'REPORT_INCOME_OBJECT': 'Отчет поступлений в бак по узлу {{item}}',
        'REPORT_INCOME_VEHICLE': 'Отчет поступлений в бак по автомобилю {{item}}',
        'REPORT_FUEL_MOVING_INTERNAL': 'Итоговый отчет движения гсм по компании',
        'REPORT_OBJECT': 'Отчет по узлу {{item}} {{item2}}',
        'REPORT_WEIGHTING': 'Отчет взвешивания по узлу {{item}} компании {{item2}}',
        'REPORT_WEIGHTING_RFID': 'Отчет взвешивания по автомобилю {{item}} компании {{item2}}',
        'REPORT_WEIGHTING_PRODUCT': 'Отчет взвешивания по продукту {{item}} компании {{item2}}',
        'REPORT_INTERNAL': 'Итоговый отчет движения ГСМ по компании',
        'PRODUCT_TYPE': 'Тип продукта: {{item}}',
        'COMPANY_HEADER': 'Компания: {{item}}',
        'REPORT_START_REMAINS': 'Остаток на начало отчета: {{item}}',
        'FOR_PERIOD': "за период с {{reportDateFrom}} по {{reportDateTo}}",
        'PORT': 'Порт',
        'LOGIN': 'Логин',
        'PASSWORD': 'Пароль',
        'TOKEN': 'Токен',
        'API_COMPANY_ID': 'ID Компании API',
        'TRUE_FUEL_CONTROL': 'Контроль',
        'SENSOR': 'Датчик',
        'SERVER': 'Сервер',
        'VEHICLE': 'Автомобиль',
        'TOTAL_ACCOUNT': 'Тотальный счетчк',
        'TANK_START': 'Бак (Начало)',
        'TANK_END': 'Бак (Конец)',
        'TANK_BAL': 'Бак',
        'TEST_CONNECTION': 'Проверка соединения',
        'OBJECTS': 'Объекты',
        'EXISTS': 'Есть',
        'COUNTER_TYPE': 'Тип счетчика',
        'CALIBRATION_COUNTER': 'Калибровочный счетчик',
        'TAG_IN': 'Тэг входной',
        'TAG_TOTAL': 'Тэг общий',
        'TAG_RFID': 'Тэг RFID',
        'TAG_RFID_VEHICLE': 'Тэг RFID авто',
        'TIMEZONE': 'Пояс',
        'FUEL_PERIOD': 'Период выборки',
        'COUNT_PERIOD': 'Сглаживание',
        'EMAIL': 'Почта',
        'COMPANY': 'Компания',
        'FIRST_NAME': 'Имя',
        'LAST_NAME': 'Фамилия',
        'PATRONYMIC': 'Отчество',
        'MENU': 'Меню',
        'ROLE': 'Роль',
        'AUTO': 'Авто',
        'THRESHOLD': 'Порог',
        'SMOOTHING': 'Сглаживание',
        'STAGE_THRESHOLD': 'Промежуточный порог',
        'GENERATE': 'Сгенерировать',
        'CODE': 'Код',
        'TOTAL_TANK_START': 'Счетчик на начало',
        'TOTAL_TANK_END': 'Счетчик на конец',
        'TOTAL_TANK': 'Итого за период по счетчику',
        'MOVE': 'Переместить',
        'STOREHOUSE_FROM': 'Склад откуда',
        'STOREHOUSE_TO': 'Склад куда',
        'ISSUED': 'Выдано',
        'FUELED': 'Заправлено',
        'CONTRACTOR': 'Контрагент',
        'CONTACT_PAY': 'Контакт платежа',
        'COMPANY_PAY': 'Компании платежа',
        'CONTACT_CLIENT': 'Контакт клиента',
        'MANAGER': 'Менеджер',
        'PAY_DATE': 'Дата платежа',
        'NODE_NAME': 'Имя узла',
        'WEIGHTING_TYPE': 'Тип взвешивания',
        'GROSS': 'Вес брутто',
        'TARE': 'Вес тары',
        'NET': 'Вес нетто',
        'CALIBRATION_ID': 'ID тарировки',
        'PARAM_IN': 'Вход',
        'PARAM_OUT_0': 'Выход 0',
        'PARAM_OUT_1': 'Выход 1',
        'PARAM_OUT_2': 'Выход 2',
        'PARAM_OUT_3': 'Выход 3',
        'STRAIT_AMOUNT': 'Сумма пролива',
        'BALANCE_SHEET':'Баланс',
        'ACTUAL_BALANCE':'Актуальный баланс',
        'RESIDUAL_DEVIATION':'Остаточное отклонение',
        'MULTIPLIER':'Множитель',
        'INN':'ИНН',
        'NOT_SELECTED': 'Не выбрано',
        'LAST_3_H': 'Последие 3 часа',
        'LAST_24_H': 'Последие 24 часа',
        'CURRENT_DAY': 'Текущий день',
        'YESTERDAY': 'Вчерашний день',
        'CURRENT_WEEK': 'Текущая неделя',
        'PREVIOUS_WEEK': 'Прошедшая неделя',
        'CURRENT_MONTH': 'Текущий месяц',
        'PREVIOUS_MONTH': 'Прошедший месяц',
        'OPERATION_ID': 'ID операции',
        'EXPIRED_LICENSE_BODY': 'Список истекших лицензий',
        'WEIGHTBRIDGE': 'Весовая станция',
        'WEIGHTBRIDGE_ID': 'ID весовой станции',
        'COMPANY_ID': 'ID компании',
        'DIVISION_ID': 'ID подразделения',
        'LATITUDE': 'Широта',
        'LONGITUDE': 'Долгота',
        'SIM_PRIMARY': 'Основная SIM',
        'SIM_SECONDARY': 'Резервная SIM',
        'CONTROLLER_PORT': 'Порт контроллера',
        'CAMERA_FRONT_IP': 'IP передней камеры',
        'CAMERA_FRONT_PORT': 'Порт передней камеры',
        'CAMERA_FRONT_USER': 'Пользователь передней камеры',
        'CAMERA_FRONT_PASS': 'Пароль передней камеры',
        'CAMERA_REAR_IP': 'IP задней камеры',
        'CAMERA_REAR_PORT': 'Порт задней камеры',
        'CAMERA_REAR_USER': 'Пользователь задней камеры',
        'CAMERA_REAR_PASS': 'Пароль задней камеры',
        'CAMERA_OFFICE_IP': 'IP камеры диспетчерской',
        'CAMERA_OFFICE_PORT': 'Порт камеры диспетчерской',
        'CAMERA_OFFICE_USER': 'Пользователь камеры диспетчерской',
        'CAMERA_OFFICE_PASS': 'Пароль камеры диспетчерской',
        'OFFICE_CROP_RECT': 'Область обрезки (диспетчерская)',
        'CAMERA_CARGO_TOP_IP': 'IP центральной камеры',
        'CAMERA_CARGO_TOP_PORT': 'Порт центральной камеры',
        'CAMERA_CARGO_TOP_USER': 'Пользователь центральной камеры',
        'CAMERA_CARGO_TOP_PASS': 'Пароль центральной камеры',
        'CARGO_TOP_CROP_RECT': 'Область обрезки (центральная камера)',
        'CARGO_TOP_PROMPT': 'Промпт для анализа груза',
        'CHAT_ID': 'ID чата Telegram',
        'PARKTRONIK_ENTRY_IP': 'IP парктроника въезда',
        'PARKTRONIK_ENTRY_PORT': 'Порт парктроника въезда',
        'PARKTRONIK_CENTER_IP': 'IP центрального парктроника',
        'PARKTRONIK_CENTER_PORT': 'Порт центрального парктроника',
        'PARKTRONIK_EXIT_IP': 'IP парктроника выезда',
        'PARKTRONIK_EXIT_PORT': 'Порт парктроника выезда',
        'TRAFFIC_LIGHT_ENTRY_IP': 'IP светофора въезда',
        'TRAFFIC_LIGHT_ENTRY_PORT': 'Порт светофора въезда',
        'TRAFFIC_LIGHT_EXIT_IP': 'IP светофора выезда',
        'TRAFFIC_LIGHT_EXIT_PORT': 'Порт светофора выезда',
        'EXTERNAL_IP': 'Внешний IP',
        'WIFI_SSID': 'Wi-Fi SSID',
        'WIFI_PASSWORD': 'Пароль Wi-Fi',
        'CONNECTION_MODE': 'Режим подключения',
        'IS_ACTIVE': 'Активна',
        'LOCAL_CONNECTION': 'Локальное подключение',
        'EXTERNAL_CONNECTION': 'Внешнее подключение',
        'NETWORK_SETTINGS': 'Сетевые параметры',
        'CAMERA_SETTINGS': 'Настройки камер',
        'PARKTRONIK_SETTINGS': 'Настройки парктроников',
        'TRAFFIC_LIGHT_SETTINGS': 'Настройки светофоров',
        'CONTROLLER_SETTINGS': 'Настройки контроллера',
        'YES': 'Да',
        'NO': 'Нет',
        'EMPTY_WEIGHT': 'Вес пустого',
        'WIDTH': 'Длина',
        'MODEL': 'Модель',
        'ENTRY': 'Взвешивание',
        'EXIT': 'Тара',
      });


      $translateProvider.translations('en', {
        'ROUTER_IP': 'Router IP',
        'PARKTRONIK_CENTER_POLL_INTERVAL_MS': 'Center parktronik poll interval (ms)',
        'PARKTRONIK_CENTER_POLL_COUNT': 'Center parktronik poll count',
        'TABLO_POLL_INTERVAL_MS': 'Tablo poll interval (ms)',
        'TABLO_POLL_COUNT': 'Tablo poll count',
        'IS_ONLINE': 'Online status',
        'LAST_SEEN': 'Last seen',
        'LICENCE': 'Licence',
        'SEND': 'Send',
        'ENTER_MESSAGE': 'Enter message',
        'USER_LIST': 'Users list',
        'MINIMUM_BALANCE': 'Minimum balance',
        'STOP_BALANCE': 'Stop balance',
        'EXPIRED_LICENSE_BODY': 'Expired licenses list',
        'REPORT_INTERNAL': 'Internal fuel moving report',
        'RESPONSIBLE': 'Responsible',
        'COMBINE': 'Combine',
        'ACCOUNT': 'Account',
        'RECALCULATE': 'Recalculate',
        'DATE': 'Date',
        'PRODUCT': 'Product',
        'DEBIT': 'Debit',
        'CREDIT': 'Credit',
        'COUNT': 'Count',
        'CAMERA_NAME': 'Camera name',
        'LAST_PROCESSING_DATE': 'Last processing date',
        'PHOTO_PROCESSING_ENABLED': 'Photo processing',
        'VIDEO_PROCESSING_ENABLED': 'Video processing',
        'STORAGE_HOURS': 'Storage time (h.)',
        'INVOISE_OPERATION_TYPE': 'Invoise operation type',
        'ACTIVE': 'Активно',
        'UPLOAD_PHOTO': 'Upload photo',
        'OBJECT': 'Object',
        'MACHINE_RFID': 'Machine RFID',
        'OBJECT_RFID': 'Object RFID',
        'TOTAL_SUM': 'Total Sum',
        'SUM': 'Sum',
        'NO_DATA': 'No Data',
        'NAME': 'Name',
        'LICENSE_DATE' : 'License date',
        'EXPIRED' : 'Expired (days)',
        'TELEGRAM': 'Telegram',
        'FILTERS': 'Filters',
        'SHOW_BLOCKED_CARDS': 'Show blocked cards',
        'CREATED_BY': 'Created by',
        'DECREASE': 'Decrease',
        'TRK_TYPE' : 'TRK type',
        'REGISTRATION_DATE': 'Registration Date',
        'OBJECTS_COUNT': 'Objects Count',
        'MAXIMUM_OBJECTS': 'Maximum Objects',
        'OWNER': 'Owner',
        'PHONE': 'Phone',
        'STATUS': 'Status',
        'BALANCE': 'Balance',
        'DAY_LIMIT': 'Day Limit',
        'LIMIT_REMAINS': 'Limit',
        'LIMIT_REMAINS_TYPE': 'Period',
        'DAY_BALANCE': 'Balance',
        'TOTALS': 'Totals',
        'FREE': 'Free',
        'GROUP_BY_OBJECTS': 'By Objects',
        'WITH_MOVES': 'With Moves',
        'DEALER': 'Dealer',
        'PRICE': 'Price',
        'SEARCH': 'Search',
        'CURRENT_FUEL_TYPE': 'Current Fuel Type',
        'GROUP_BY_OBJECTS_TOOLTIP': 'Group by objects',
        'ONLY_WITH_MOVES_TOOLTIP': 'Only with moves',
        'LOCK': 'Lock',
        'UNLOCK': 'Unlock',
        'LAST_RECEIVED_PACKAGE_TIME': 'Last package time',
        'NOT_SENT_MESSAGES_COUNT': 'Not sent messages',
        'LIMIT_TYPE': 'RFID Type',
        'LIMIT_CARD': 'Limit card',
        'UNLIMITED_CARD': 'Unlimited card',
        'TYPE': 'Type',
        'UNITS': 'Units',
        'SOURCE': 'Source',
        'CALIBRATION': 'Calibration',
        'INPUT': 'Input Value',
        'CALIBRATION_VALUE': 'Calibration Value',
        'ADDRESS': 'Address',
        'STOREHOUSE': 'Storehouse',
        'RELATED_STOREHOUSE': 'Related storehouse',
        'DIVISION': 'Division',
        'LICENSE_PLATE': 'License plate',
        'TRAILER_PLATE': 'Trailer plate',
        'CARGO': 'Cargo',
        'BRAND': 'Brand',
        'DOCUMENT': 'Document',
        'GARAGE_NUMBER': 'Garage number',
        'VOLUME': 'Volume',
        'SIZE': 'Size',
        'IMPORT': 'Import',
        'EXPORT': 'Export',
        'LEVEL': 'Level',
        'LEVEL_END': 'Final Level',
        'LEVEL_START': 'Init. Level',
        'LEVEL_REMAINS': 'Init. Remains',
        'LEVEL_FINAL': 'Final Remains',
        'PRODUCT_TYPE': 'Product: {{item}}',
        'COMPANY_HEADER': 'Company: {{item}}',
        'TEMPERATURE': 'Temperature',
        'DENSITY': 'Density',
        'WEIGHT': 'Weight',
        'WATER': 'Water',
        'LEVEL_CM': 'Level (cm)',
        'CHARTS': 'Charts',
        'CONSUMPTION': 'Consumption',
        'INVENTORY': 'Inventory',
        'INTERNAL_DEBIT': 'Internal debit',
        'INTERNAL_CREDIT': 'Internal credit',
        'VEHICLE_CONSUMPTION': 'Vehicle consumption',
        'DISTRIBUTOR': 'Distributor',
        'INCOME': 'Income',
        'FINAL_COUNTER': 'Final Counter',
        'DELIVERY_SUM': 'Delivery sum',
        'DEVIATION': 'Deviation',
        'INTERNAL_INCOME': 'Internal Income',
        'INTERNAL_CONSUMPTION': 'Internal Consumption',
        'ITN': 'ITN',
        'RECIPIENT': 'Recipient',
        'SENDER': 'Sender',
        'SUPPLIER': 'Supplier',
        'TANK': 'Tank',
        'TEMPERATURE_DOC': 'Temperature upon shipment',
        'TEMPERATURE_IN': 'Temperature at reception',
        'TEMPERATURE_DEVIATION': 'Temperature deviation',
        'DENSITY_DOC': 'Density upon shipment',
        'DENSITY_IN': 'Density at reception',
        'DENSITY_DEVIATION': 'Density deviation',
        'LITRES_COUNTER_DOC': 'Liters upon shipment',
        'LITRES_COUNTER_IN': 'Liters at reception',
        'LITRES_COUNTER_DEVIATION': 'Liters deviation',
        'LITRES_DENSITY_DOC': 'Liters upon shipment by density',
        'LITRES_DENSITY_IN': 'Liters at reception by density',
        'LITRES_DENSITY_DEVIATION': 'Liters deviation by density',
        'WEIGHT_DOC': 'Weight upon shipment',
        'WEIGHT_IN': 'Weight at reception',
        'WEIGHT_DEVIATION': 'Weight deviation',
        'COMMENT': 'Comment',
        'PRODUCT_NAME_DOC': 'Product name by document',
        'DOC_NUM': 'Document number',
        'DOC_DATE': 'Document date',
        'USER': 'User',
        'CREATED_AT': 'Created At',
        'UPDATED_AT': 'Updated At',
        'RUN_DATE': 'Run date',
        'RUN_TIME': 'Run time',
        'PERIOD': 'Period',
        'PIN_CODE': 'PIN',
        'EMPLOYEE': 'Employee',
        'DATE_FROM': 'From',
        'DATE_TO': 'To',
        'SELECT_ALL': 'Select All',
        'ALL': 'All',
        'OFFSET': 'Offset',
        'CORRECTION': 'Correction',
        'DESCRIPTION': 'Description',
        'LOCATION': 'Location',
        'ROUTER_IMEI': 'Router IMEI',
        'CONTROLLER_IP': 'Controller ip',
        'PORT': 'Port',
        'LOGIN': 'Login',
        'PASSWORD': 'Password',
        'TOKEN': 'Token',
        'API_COMPANY_ID': 'API Company ID',
        'TRUE_FUEL_CONTROL': 'Control',
        'SENSOR': 'Sensor',
        'SERVER': 'Server',
        'VEHICLE': 'Vehicle',
        'TOTAL_ACCOUNT': 'Total Account',
        'TANK_START': 'Tank (Start)',
        'TANK_END': 'Tank (End)',
        'TANK_BAL': 'Tank',
        'TEST_CONNECTION': 'Test Connection',
        'OBJECTS': 'Objects',
        'EXISTS': 'Exists',
        'COUNTER_TYPE': 'Counter type',
        'CALIBRATION_COUNTER': 'Calibration counter',
        'TAG_IN': 'Tag in',
        'TAG_TOTAL': 'Tag total',
        'TAG_RFID': 'RFID tag',
        'TAG_RFID_VEHICLE': 'Vehicle RFID tag',
        'TIMEZONE': 'Timezone',
        'FUEL_PERIOD': 'Sample period',
        'COUNT_PERIOD': 'Smoothing',
        'EMAIL': 'Email',
        'COMPANY': 'Company',
        'FIRST_NAME': 'First name',
        'LAST_NAME': 'Last name',
        'PATRONYMIC': 'Patronymic',
        'MENU': 'Menu',
        'ROLE': 'Role',
        'AUTO': 'Auto',
        'THRESHOLD': 'Threshold',
        'SMOOTHING': 'Smoothing',
        'STAGE_THRESHOLD': 'Stage threshold',
        'GENERATE': 'Generate',
        'CODE': 'Code',
        'TOTAL_TANK_START': 'TOTAL START',
        'TOTAL_TANK_END': 'TOTAL END',
        'TOTAL_TANK': 'TOTAL SUM',
        'MOVE': 'Move',
        'STOREHOUSE_FROM': 'Storehouse from',
        'STOREHOUSE_TO': 'Storehouse to',
        'ISSUED': 'Issued',
        'FUELED': 'Fueled',
        'CONTRACTOR': 'Contractor',
        'CONTACT_PAY': 'Pay contact',
        'COMPANY_PAY': 'Pay company',
        'CONTACT_CLIENT': 'Client contact',
        'MANAGER': 'Manager',
        'PAY_DATE': 'Pay date',
        'NODE_NAME': 'Node name',
        'WEIGHTING_TYPE': 'Weighting type',
        'GROSS': 'Gross',
        'TARE': 'Tare',
        'NET': 'Net',
        'CALIBRATION_ID': 'Calibration ID',
        'PARAM_IN': 'In',
        'PARAM_OUT_0': 'Out 0',
        'PARAM_OUT_1': 'Out 1',
        'PARAM_OUT_2': 'Out 2',
        'PARAM_OUT_3': 'Out 3',
        'STRAIT_AMOUNT': 'Strait amount',
        'BALANCE_SHEET':'Balance sheet',
        'ACTUAL_BALANCE':'Actual balance',
        'RESIDUAL_DEVIATION':'Residual deviation',
        'BY_REMAINS': 'By remains',
        'BY_REMAINS_DETAILED': 'By remains (detailed)',
        'BY_DAYS': 'By days',
        'CONTROL': 'Control',
        'MULTIPLIER':'Multiplier',
        'INN':'INN',
        'NOT_SELECTED': 'Not selected',
        'LAST_3_H': 'Last 3 hours',
        'LAST_24_H': 'Last 24 hours',
        'CURRENT_DAY': 'Current day',
        'YESTERDAY': 'Yesterday',
        'CURRENT_WEEK': 'Current week',
        'PREVIOUS_WEEK': 'Previous week',
        'CURRENT_MONTH': 'Current month',
        'PREVIOUS_MONTH': 'Previous month',
        'REPORT_TOTALS_BY_RFID': "Totals by RFIDs",
        'REPORT_TOTALS_BY_VEHICLE': "Totals by vehicles",
        'REPORT_DETAILED_BY_RFID': "Detailed report by RFIDs",
        'REPORT_BY_RFID': "Report by RFID {{item}}",
        'REPORT_BY_DIVISION': 'Report by division {{item}}',
        'REPORT_FUEL_MOVING': 'Report fuel moving',
        'REPORT_FUEL_MOVING_STOREHOUSE': 'Report fuel moving by storehouse {{item}}',
        'REPORT_INCOME_OBJECT': 'Report: object income {{item}}',
        'REPORT_INCOME_VEHICLE': 'Report: vehicle income {{item}}',
        'REPORT_OBJECT': 'Report by object {{item}} {{item2}}',
        'REPORT_WEIGHTING': 'Report: weighting by object {{item}} of company {{item2}}',
        'REPORT_WEIGHTING_RFID': 'Report: weighting by rfid {{item}} of company {{item2}}',
        'REPORT_WEIGHTING_PRODUCT': 'Report: weighting by product {{item}} of company {{item2}}',
        'REPORT_START_REMAINS': 'Report start remains: {{item}}',
        'REPORT_FUEL_MOVING_INTERNAL': 'Report: internal fuel moving',
        'FOR_PERIOD': "for period: from {{reportDateFrom}} to {{reportDateTo}}",
        'OPERATION_ID': 'Operation ID',
        'WEIGHTBRIDGE': 'Weightbridge',
        'WEIGHTBRIDGE_ID': 'Weightbridge ID',
        'COMPANY_ID': 'Company ID',
        'DIVISION_ID': 'Division ID',
        'LATITUDE': 'Latitude',
        'LONGITUDE': 'Longitude',
        'SIM_PRIMARY': 'Primary SIM',
        'SIM_SECONDARY': 'Secondary SIM',
        'CONTROLLER_PORT': 'Controller port',
        'CAMERA_FRONT_IP': 'Front camera IP',
        'CAMERA_FRONT_PORT': 'Front camera port',
        'CAMERA_FRONT_USER': 'Front camera user',
        'CAMERA_FRONT_PASS': 'Front camera password',
        'CAMERA_REAR_IP': 'Rear camera IP',
        'CAMERA_REAR_PORT': 'Rear camera port',
        'CAMERA_REAR_USER': 'Rear camera user',
        'CAMERA_REAR_PASS': 'Rear camera password',
        'CAMERA_OFFICE_IP': 'Office camera IP',
        'CAMERA_OFFICE_PORT': 'Office camera port',
        'CAMERA_OFFICE_USER': 'Office camera username',
        'CAMERA_OFFICE_PASS': 'Office camera password',
        'OFFICE_CROP_RECT': 'Crop area (office camera)',
        'CAMERA_CARGO_TOP_IP': 'Top cargo camera IP',
        'CAMERA_CARGO_TOP_PORT': 'Top cargo camera port',
        'CAMERA_CARGO_TOP_USER': 'Top cargo camera username',
        'CAMERA_CARGO_TOP_PASS': 'Top cargo camera password',
        'CARGO_TOP_CROP_RECT': 'Crop area (top cargo camera)',
        'CARGO_TOP_PROMPT': 'Cargo analysis prompt',
        'CHAT_ID': 'Telegram chat ID',
        'PARKTRONIK_ENTRY_IP': 'Entry parktronik IP',
        'PARKTRONIK_ENTRY_PORT': 'Entry parktronik port',
        'PARKTRONIK_CENTER_IP': 'Center parktronik IP',
        'PARKTRONIK_CENTER_PORT': 'Center parktronik port',
        'PARKTRONIK_EXIT_IP': 'Exit parktronik IP',
        'PARKTRONIK_EXIT_PORT': 'Exit parktronik port',
        'TRAFFIC_LIGHT_ENTRY_IP': 'Entry traffic light IP',
        'TRAFFIC_LIGHT_ENTRY_PORT': 'Entry traffic light port',
        'TRAFFIC_LIGHT_EXIT_IP': 'Exit traffic light IP',
        'TRAFFIC_LIGHT_EXIT_PORT': 'Exit traffic light port',
        'EXTERNAL_IP': 'External IP',
        'WIFI_SSID': 'Wi-Fi SSID',
        'WIFI_PASSWORD': 'Wi-Fi password',
        'CONNECTION_MODE': 'Connection mode',
        'IS_ACTIVE': 'Is active',
        'LOCAL_CONNECTION': 'Local connection',
        'EXTERNAL_CONNECTION': 'External connection',
        'NETWORK_SETTINGS': 'Network settings',
        'CAMERA_SETTINGS': 'Camera settings',
        'PARKTRONIK_SETTINGS': 'Parktronik settings',
        'TRAFFIC_LIGHT_SETTINGS': 'Traffic light settings',
        'CONTROLLER_SETTINGS': 'Controller settings',
        'YES': 'Yes',
        'NO': 'No',
        'EMPTY_WEIGHT': 'Empty weight',
        'WIDTH': 'Width',
        'MODEL': 'Model',
        'ENTRY': 'Entry',
        'EXIT': 'Exit',
      });


      //Секция ниже служит для локализации арабского языка (в разработке)
      $translateProvider.translations('ar', {
        'ROUTER_IP': 'Router IP',
        'PARKTRONIK_CENTER_POLL_INTERVAL_MS': 'Center parktronik poll interval (ms)',
        'PARKTRONIK_CENTER_POLL_COUNT': 'Center parktronik poll count',
        'TABLO_POLL_INTERVAL_MS': 'Tablo poll interval (ms)',
        'TABLO_POLL_COUNT': 'Tablo poll count',
        'IS_ONLINE': 'Online status',
        'LAST_SEEN': 'Last seen',
        'LICENCE': 'Licence',
        'SEND': 'Send',
        'ENTER_MESSAGE': 'Enter message',
        'USER_LIST': 'Users list',
        'MINIMUM_BALANCE': 'Minimum balance',
        'STOP_BALANCE': 'Stop balance',
        'EXPIRED_LICENSE_BODY': 'Expired licenses list',
        'REPORT_INTERNAL': 'Internal fuel moving report',
        'RESPONSIBLE': 'Responsible',
        'COMBINE': 'Combine',
        'ACCOUNT': 'Account',
        'RECALCULATE': 'Recalculate',
        'DATE': 'Date',
        'PRODUCT': 'Product',
        'DEBIT': 'Debit',
        'CREDIT': 'Credit',
        'COUNT': 'Count',
        'CAMERA_NAME': 'Camera name',
        'LAST_PROCESSING_DATE': 'Last processing date',
        'PHOTO_PROCESSING_ENABLED': 'Photo processing',
        'VIDEO_PROCESSING_ENABLED': 'Video processing',
        'STORAGE_HOURS': 'Storage time (h.)',
        'INVOISE_OPERATION_TYPE': 'Invoise operation type',
        'ACTIVE': 'Активно',
        'UPLOAD_PHOTO': 'Upload photo',
        'OBJECT': 'Object',
        'MACHINE_RFID': 'Machine RFID',
        'OBJECT_RFID': 'Object RFID',
        'TOTAL_SUM': 'Total Sum',
        'SUM': 'Sum',
        'NO_DATA': 'No Data',
        'NAME': 'Name',
        'LICENSE_DATE' : 'License date',
        'EXPIRED' : 'Expired (days)',
        'TELEGRAM': 'Telegram',
        'FILTERS': 'Filters',
        'SHOW_BLOCKED_CARDS': 'Show blocked cards',
        'CREATED_BY': 'Created by',
        'DECREASE': 'Decrease',
        'TRK_TYPE' : 'TRK type',
        'REGISTRATION_DATE': 'Registration Date',
        'OBJECTS_COUNT': 'Objects Count',
        'MAXIMUM_OBJECTS': 'Maximum Objects',
        'OWNER': 'Owner',
        'PHONE': 'Phone',
        'STATUS': 'Status',
        'BALANCE': 'Balance',
        'DAY_LIMIT': 'Day Limit',
        'LIMIT_REMAINS': 'Limit',
        'LIMIT_REMAINS_TYPE': 'Period',
        'DAY_BALANCE': 'Balance',
        'TOTALS': 'Totals',
        'FREE': 'Free',
        'GROUP_BY_OBJECTS': 'By Objects',
        'WITH_MOVES': 'With Moves',
        'DEALER': 'Dealer',
        'PRICE': 'Price',
        'SEARCH': 'Search',
        'CURRENT_FUEL_TYPE': 'Current Fuel Type',
        'GROUP_BY_OBJECTS_TOOLTIP': 'Group by objects',
        'ONLY_WITH_MOVES_TOOLTIP': 'Only with moves',
        'LOCK': 'Lock',
        'UNLOCK': 'Unlock',
        'LAST_RECEIVED_PACKAGE_TIME': 'Last package time',
        'NOT_SENT_MESSAGES_COUNT': 'Not sent messages',
        'LIMIT_TYPE': 'RFID Type',
        'LIMIT_CARD': 'Limit card',
        'UNLIMITED_CARD': 'Unlimited card',
        'TYPE': 'Type',
        'UNITS': 'Units',
        'SOURCE': 'Source',
        'CALIBRATION': 'Calibration',
        'INPUT': 'Input Value',
        'CALIBRATION_VALUE': 'Calibration Value',
        'ADDRESS': 'Address',
        'STOREHOUSE': 'Storehouse',
        'RELATED_STOREHOUSE': 'Related storehouse',
        'DIVISION': 'Division',
        'LICENSE_PLATE': 'License plate',
        'TRAILER_PLATE': 'Trailer plate',
        'CARGO': 'Cargo',
        'BRAND': 'Brand',
        'DOCUMENT': 'Document',
        'GARAGE_NUMBER': 'Garage number',
        'VOLUME': 'Volume',
        'SIZE': 'Size',
        'IMPORT': 'Import',
        'EXPORT': 'Export',
        'LEVEL': 'Level',
        'LEVEL_END': 'Final Level',
        'LEVEL_START': 'Init. Level',
        'LEVEL_REMAINS': 'Init. Remains',
        'LEVEL_FINAL': 'Final Remains',
        'PRODUCT_TYPE': 'Product: {{item}}',
        'COMPANY_HEADER': 'Company: {{item}}',
        'TEMPERATURE': 'Temperature',
        'DENSITY': 'Density',
        'WEIGHT': 'Weight',
        'WATER': 'Water',
        'LEVEL_CM': 'Level (cm)',
        'CHARTS': 'Charts',
        'CONSUMPTION': 'Consumption',
        'INVENTORY': 'Inventory',
        'INTERNAL_DEBIT': 'Internal debit',
        'INTERNAL_CREDIT': 'Internal credit',
        'VEHICLE_CONSUMPTION': 'Vehicle consumption',
        'DISTRIBUTOR': 'Distributor',
        'INCOME': 'Income',
        'FINAL_COUNTER': 'Final Counter',
        'DELIVERY_SUM': 'Delivery sum',
        'DEVIATION': 'Deviation',
        'INTERNAL_INCOME': 'Internal Income',
        'INTERNAL_CONSUMPTION': 'Internal Consumption',
        'ITN': 'ITN',
        'RECIPIENT': 'Recipient',
        'SENDER': 'Sender',
        'SUPPLIER': 'Supplier',
        'TANK': 'Tank',
        'TEMPERATURE_DOC': 'Temperature upon shipment',
        'TEMPERATURE_IN': 'Temperature at reception',
        'TEMPERATURE_DEVIATION': 'Temperature deviation',
        'DENSITY_DOC': 'Density upon shipment',
        'DENSITY_IN': 'Density at reception',
        'DENSITY_DEVIATION': 'Density deviation',
        'LITRES_COUNTER_DOC': 'Liters upon shipment',
        'LITRES_COUNTER_IN': 'Liters at reception',
        'LITRES_COUNTER_DEVIATION': 'Liters deviation',
        'LITRES_DENSITY_DOC': 'Liters upon shipment by density',
        'LITRES_DENSITY_IN': 'Liters at reception by density',
        'LITRES_DENSITY_DEVIATION': 'Liters deviation by density',
        'WEIGHT_DOC': 'Weight upon shipment',
        'WEIGHT_IN': 'Weight at reception',
        'WEIGHT_DEVIATION': 'Weight deviation',
        'COMMENT': 'Comment',
        'PRODUCT_NAME_DOC': 'Product name by document',
        'DOC_NUM': 'Document number',
        'DOC_DATE': 'Document date',
        'USER': 'User',
        'CREATED_AT': 'Created At',
        'UPDATED_AT': 'Updated At',
        'RUN_DATE': 'Run date',
        'RUN_TIME': 'Run time',
        'PERIOD': 'Period',
        'PIN_CODE': 'PIN',
        'EMPLOYEE': 'Employee',
        'DATE_FROM': 'From',
        'DATE_TO': 'To',
        'SELECT_ALL': 'Select All',
        'ALL': 'All',
        'OFFSET': 'Offset',
        'CORRECTION': 'Correction',
        'DESCRIPTION': 'Description',
        'LOCATION': 'Location',
        'ROUTER_IMEI': 'Router IMEI',
        'CONTROLLER_IP': 'Controller ip',
        'PORT': 'Port',
        'LOGIN': 'Login',
        'PASSWORD': 'Password',
        'TOKEN': 'Token',
        'API_COMPANY_ID': 'API Company ID',
        'TRUE_FUEL_CONTROL': 'Control',
        'SENSOR': 'Sensor',
        'SERVER': 'Server',
        'VEHICLE': 'Vehicle',
        'TOTAL_ACCOUNT': 'Total Account',
        'TANK_START': 'Tank (Start)',
        'TANK_END': 'Tank (End)',
        'TANK_BAL': 'Tank',
        'TEST_CONNECTION': 'Test Connection',
        'OBJECTS': 'Objects',
        'EXISTS': 'Exists',
        'COUNTER_TYPE': 'Counter type',
        'CALIBRATION_COUNTER': 'Calibration counter',
        'TAG_IN': 'Tag in',
        'TAG_TOTAL': 'Tag total',
        'TAG_RFID': 'RFID tag',
        'TAG_RFID_VEHICLE': 'Vehicle RFID tag',
        'TIMEZONE': 'Timezone',
        'FUEL_PERIOD': 'Sample period',
        'COUNT_PERIOD': 'Smoothing',
        'EMAIL': 'Email',
        'COMPANY': 'Company',
        'FIRST_NAME': 'First name',
        'LAST_NAME': 'Last name',
        'PATRONYMIC': 'Patronymic',
        'MENU': 'Menu',
        'ROLE': 'Role',
        'AUTO': 'Auto',
        'THRESHOLD': 'Threshold',
        'SMOOTHING': 'Smoothing',
        'STAGE_THRESHOLD': 'Stage threshold',
        'GENERATE': 'Generate',
        'CODE': 'Code',
        'TOTAL_TANK_START': 'TOTAL START',
        'TOTAL_TANK_END': 'TOTAL END',
        'TOTAL_TANK': 'TOTAL SUM',
        'MOVE': 'Move',
        'STOREHOUSE_FROM': 'Storehouse from',
        'STOREHOUSE_TO': 'Storehouse to',
        'ISSUED': 'Issued',
        'FUELED': 'Fueled',
        'CONTRACTOR': 'Contractor',
        'CONTACT_PAY': 'Pay contact',
        'COMPANY_PAY': 'Pay company',
        'CONTACT_CLIENT': 'Client contact',
        'MANAGER': 'Manager',
        'PAY_DATE': 'Pay date',
        'NODE_NAME': 'Node name',
        'WEIGHTING_TYPE': 'Weighting type',
        'GROSS': 'Gross',
        'TARE': 'Tare',
        'NET': 'Net',
        'CALIBRATION_ID': 'Calibration ID',
        'PARAM_IN': 'In',
        'PARAM_OUT_0': 'Out 0',
        'PARAM_OUT_1': 'Out 1',
        'PARAM_OUT_2': 'Out 2',
        'PARAM_OUT_3': 'Out 3',
        'STRAIT_AMOUNT': 'Strait amount',
        'BALANCE_SHEET':'Balance sheet',
        'ACTUAL_BALANCE':'Actual balance',
        'RESIDUAL_DEVIATION':'Residual deviation',
        'BY_REMAINS': 'By remains',
        'BY_REMAINS_DETAILED': 'By remains (detailed)',
        'BY_DAYS': 'By days',
        'CONTROL': 'Control',
        'MULTIPLIER':'Multiplier',
        'INN':'INN',
        'NOT_SELECTED': 'Not selected',
        'LAST_3_H': 'Last 3 hours',
        'LAST_24_H': 'Last 24 hours',
        'CURRENT_DAY': 'Current day',
        'YESTERDAY': 'Yesterday',
        'CURRENT_WEEK': 'Current week',
        'PREVIOUS_WEEK': 'Previous week',
        'CURRENT_MONTH': 'Current month',
        'PREVIOUS_MONTH': 'Previous month',
        'REPORT_TOTALS_BY_RFID': "Totals by RFIDs",
        'REPORT_TOTALS_BY_VEHICLE': "Totals by vehicles",
        'REPORT_DETAILED_BY_RFID': "Detailed report by RFIDs",
        'REPORT_BY_RFID': "Report by RFID {{item}}",
        'REPORT_BY_DIVISION': 'Report by division {{item}}',
        'REPORT_FUEL_MOVING': 'Report fuel moving',
        'REPORT_FUEL_MOVING_STOREHOUSE': 'Report fuel moving by storehouse {{item}}',
        'REPORT_INCOME_OBJECT': 'Report: object income {{item}}',
        'REPORT_INCOME_VEHICLE': 'Report: vehicle income {{item}}',
        'REPORT_OBJECT': 'Report by object {{item}} {{item2}}',
        'REPORT_WEIGHTING': 'Report: weighting by object {{item}} of company {{item2}}',
        'REPORT_WEIGHTING_RFID': 'Report: weighting by rfid {{item}} of company {{item2}}',
        'REPORT_WEIGHTING_PRODUCT': 'Report: weighting by product {{item}} of company {{item2}}',
        'REPORT_START_REMAINS': 'Report start remains: {{item}}',
        'REPORT_FUEL_MOVING_INTERNAL': 'Report: internal fuel moving',
        'FOR_PERIOD': "for period: from {{reportDateFrom}} to {{reportDateTo}}",
        'OPERATION_ID': 'Operation ID',
        'WEIGHTBRIDGE': 'Weightbridge',
        'WEIGHTBRIDGE_ID': 'Weightbridge ID',
        'COMPANY_ID': 'Company ID',
        'DIVISION_ID': 'Division ID',
        'LATITUDE': 'Latitude',
        'LONGITUDE': 'Longitude',
        'SIM_PRIMARY': 'Primary SIM',
        'SIM_SECONDARY': 'Secondary SIM',
        'CONTROLLER_PORT': 'Controller port',
        'CAMERA_FRONT_IP': 'Front camera IP',
        'CAMERA_FRONT_PORT': 'Front camera port',
        'CAMERA_FRONT_USER': 'Front camera user',
        'CAMERA_FRONT_PASS': 'Front camera password',
        'CAMERA_REAR_IP': 'Rear camera IP',
        'CAMERA_REAR_PORT': 'Rear camera port',
        'CAMERA_REAR_USER': 'Rear camera user',
        'CAMERA_REAR_PASS': 'Rear camera password',
        'CAMERA_OFFICE_IP': 'Office camera IP',
        'CAMERA_OFFICE_PORT': 'Office camera port',
        'CAMERA_OFFICE_USER': 'Office camera username',
        'CAMERA_OFFICE_PASS': 'Office camera password',
        'OFFICE_CROP_RECT': 'Crop area (office camera)',
        'CAMERA_CARGO_TOP_IP': 'Top cargo camera IP',
        'CAMERA_CARGO_TOP_PORT': 'Top cargo camera port',
        'CAMERA_CARGO_TOP_USER': 'Top cargo camera username',
        'CAMERA_CARGO_TOP_PASS': 'Top cargo camera password',
        'CARGO_TOP_CROP_RECT': 'Crop area (top cargo camera)',
        'CARGO_TOP_PROMPT': 'Cargo analysis prompt',
        'CHAT_ID': 'Telegram chat ID',
        'PARKTRONIK_ENTRY_IP': 'Entry parktronik IP',
        'PARKTRONIK_ENTRY_PORT': 'Entry parktronik port',
        'PARKTRONIK_CENTER_IP': 'Center parktronik IP',
        'PARKTRONIK_CENTER_PORT': 'Center parktronik port',
        'PARKTRONIK_EXIT_IP': 'Exit parktronik IP',
        'PARKTRONIK_EXIT_PORT': 'Exit parktronik port',
        'TRAFFIC_LIGHT_ENTRY_IP': 'Entry traffic light IP',
        'TRAFFIC_LIGHT_ENTRY_PORT': 'Entry traffic light port',
        'TRAFFIC_LIGHT_EXIT_IP': 'Exit traffic light IP',
        'TRAFFIC_LIGHT_EXIT_PORT': 'Exit traffic light port',
        'EXTERNAL_IP': 'External IP',
        'WIFI_SSID': 'Wi-Fi SSID',
        'WIFI_PASSWORD': 'Wi-Fi password',
        'CONNECTION_MODE': 'Connection mode',
        'IS_ACTIVE': 'Is active',
        'LOCAL_CONNECTION': 'Local connection',
        'EXTERNAL_CONNECTION': 'External connection',
        'NETWORK_SETTINGS': 'Network settings',
        'CAMERA_SETTINGS': 'Camera settings',
        'PARKTRONIK_SETTINGS': 'Parktronik settings',
        'TRAFFIC_LIGHT_SETTINGS': 'Traffic light settings',
        'CONTROLLER_SETTINGS': 'Controller settings',
        'YES': 'Yes',
        'NO': 'No',
        'EMPTY_WEIGHT': 'Empty weight',
        'WIDTH': 'Width',
        'MODEL': 'Model',
        'ENTRY': 'Entry',
        'EXIT': 'Exit',
      });

      $translateProvider.preferredLanguage('ru');

      ChartJsProvider.setOptions({ responsive: false });
    }])
    .run(['$rootScope', '$translate', '$cookies', 'UserService', '$q', function ($rootScope, $translate, $cookies, UserService, $q) {
     $rootScope.languages = [
         { value: 'ru', label: 'Русский (RU)' },
         { value: 'en', label: 'English (EN)' },
         { value: 'ar', label: 'العربية (AR)' } // Исправлено название языка
     ];
      let langCookie = $cookies.get('org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE');
      var lang = langCookie ? langCookie : 'ru';
      moment.locale(lang);
      $translate.use(lang);

      $rootScope.changeLang = function (lang) {
        var url = window.location.origin + '?lang=' + lang;
        window.location.href = url;
      };

      $rootScope.isValidDate = function (date) {
        return angular.isDate(date);
      };

      $rootScope.formatDate = function (dateStr, format){
        if (!dateStr) {
          return null;
        }
        return moment(dateStr).format(format);
      }

      $rootScope.isSameDate = function (date1, date2) {
        return moment(date1).isSame(moment(date2), 'day');
      }

      $rootScope.setByRemains = function (byRemains) {
        UserService.request.setByRemains({byRemains: byRemains}, function (result) {
          $rootScope.currentUser.byRemains = byRemains;
          $rootScope.$broadcast('setByRemains', {byRemains: byRemains});
        }, function (error) {
          toaster.pop('error', "", error.data.message);
        });
      }

      $rootScope.stringToNumber = function (str) {
        return parseFloat(str);
      }

      $rootScope.nonZeroRegexp = /^(0*[a-zA-Z1-9_-]+0*)+$/;
      $rootScope.nonZeroNumericRegexp = /^(0*[1-9\.]+0*)+$/;
      $rootScope.decimalPattern = /^(\d*\.)?\d+$|^N\/A$/
      $rootScope.validDateTimePattern = /^(?=\d)(?:(?:31(?!.(?:0?[2469]|11))|(?:30|29)(?!.0?2)|29(?=.0?2.(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(?:\x20|$))|(?:2[0-8]|1\d|0?[1-9]))([-./])(?:1[012]|0?[1-9])\1(?:1[6-9]|[2-9]\d)?\d\d(?:(?=\x20\d)\x20|$))?(((0?[1-9]|1[012])(:[0-5]\d){0,2}(\x20[AP]M))|([01]\d|2[0-3])(:[0-5]\d){1,2})?$/

      $rootScope.exportExcel = function (url, method, params, sheetName) {
        var xhr = new XMLHttpRequest();
        xhr.open(method, url, true);
        xhr.withCredentials = true;
        xhr.responseType = 'arraybuffer';
        xhr.timeout = 30 * 60 * 1000;//30 min
        xhr.onload = function (e) {
          switch (this.status) {
            case 200:
              var blob = new Blob([this.response], {type: 'application/vnd.ms-excel'});
              if (navigator.appVersion.toString().indexOf('.NET') > 0 || navigator.appVersion.toString().indexOf("Edge") > -1) { // for IE browser
                window.navigator.msSaveBlob(blob, sheetName);
              } else {
                var url = URL.createObjectURL(blob);
                var a = document.createElement("a");
                a.href = url;
                a.download = sheetName;
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
              }
              break;
            case 401: //Unauthorized
              $rootScope.logout();
              break;
            default:
              alert("Unable to download Excel");
              break;
          }
        };
        xhr.onerror = function () {
          alert("Unable to download Excel");
        };
        xhr.send(params);
      };

    }])
})();
