(function () {
  'use strict';

  const apiPrefix = '/api/v1';

  angular
    .module('app.config', [])
    .constant('API', {
      menuItems: apiPrefix + '/menu_items',
      updateStartMenu: apiPrefix + '/update_start_menu',
      getChildMenuItems: apiPrefix + '/get_child_menu_items',
      getParentMenuItems: apiPrefix + '/get_parent_menu_items',
      getAllMenuItems: apiPrefix + '/get_all_menu_items',

      currentUser: apiPrefix + '/current_user',
      createUser: apiPrefix + '/create_user',
      getUsers: apiPrefix + '/get_users',
      sendPassword: apiPrefix + '/send_password',
      setTheme: apiPrefix + '/set_theme',
      setByRemains: apiPrefix + '/set_by_remains',

      accountData: apiPrefix + '/account_data',
      moveCount: apiPrefix + '/move_count',
      updateCurrentProduct: apiPrefix + '/update_current_product',
      updateCurrentDivision: apiPrefix + '/update_current_division',
      updateCurrentPartner: apiPrefix + '/update_current_partner',
      getCurrentAccountData: apiPrefix + '/current_account_data',

      getCompanyList: apiPrefix + '/get_list_company_transformed',
      deleteCompany: apiPrefix + '/delete_company',
      updateCompanyName: apiPrefix + '/update_company_name',
      setDefaultCompany: apiPrefix + '/set_default_company',
      addCompany: apiPrefix + '/add_company',
      company: apiPrefix + '/company',

      getObjects: apiPrefix + '/get_objects',
      getObjectsByProduct: apiPrefix + '/get_objects_by_product',
      getObjectsForCurrentUser: apiPrefix + '/report_list_imei_current_user',
      deleteObjectByImei: apiPrefix + '/delete_object_by_imei',
      updateObjectName: apiPrefix + '/update_object_name',
      addObject: apiPrefix + '/add_object',
      getProducts: apiPrefix + '/get_products',
      getTrkTypes: apiPrefix + '/get_trk_types',
      setDataExchange: apiPrefix + '/set_data_exchange',
      mapAllObjectsToRfid: apiPrefix + '/map_all_objects_to_rfid',
      mapObjectToRfid: apiPrefix + '/map_object_to_rfid',
      getObjectData: apiPrefix + '/get_object_data',
      getExpiredLicenses: apiPrefix + '/get_expired_licenses',

      getObjectsRfidForCurrentUser: apiPrefix + '/rfid_list_current_user',
      addRfid: apiPrefix + '/add_rfid',
      lockRfid: apiPrefix + '/rfid_lock',
      unlockRfid: apiPrefix + '/rfid_delock',
      updateRfidName: apiPrefix + '/set_name_rfid_tag',
      deleteRfid: apiPrefix + '/delete_rfid',
      getObjectRfidType: apiPrefix + '/object_rfid_type',
      getRfidObjects: apiPrefix + '/get_rfid_objects',
      getLimitTypes: apiPrefix + '/get_limit_types',
      recalculateRfid: apiPrefix + '/recalculate_balance',

      getAccountOperations: apiPrefix + '/account_operations',
      getObjectRfidBalance: apiPrefix + '/object_rfid_balance',
      getObjectBalance: apiPrefix + '/object_balance',
      setLoadApi: apiPrefix + '/set_load_api',
      setVehicleId: apiPrefix + '/set_vehicle_id',
      getTankData: apiPrefix + '/get_tank_data',
      getWialonIncome: apiPrefix + '/get_wialon_income',
      toggleDeleteStatus: apiPrefix + '/toggle_delete_status',

      getSensorsByObject: apiPrefix + '/get_sensors_by_object',
      getSensor: apiPrefix + '/get_sensor',
      deleteSensor: apiPrefix + '/delete_sensor',
      getSensorTypes: apiPrefix + '/get_sensor_types',
      saveSensor: apiPrefix + '/save_sensor',

      getSensorsByTank: apiPrefix + '/get_sensors_by_tank',
      getTankSensor: apiPrefix + '/get_tank_sensor',
      deleteTankSensor: apiPrefix + '/delete_tank_sensor',
      getTankSensorTypes: apiPrefix + '/get_tank_sensor_types',
      saveTankSensor: apiPrefix + '/save_tank_sensor',
      getSourceData: apiPrefix + '/get_source_data',

      division: apiPrefix + '/division',
      dealer: apiPrefix + '/dealer',
      companyAccountOperations: apiPrefix + '/company_account_operations',
      weightOperations: apiPrefix + '/weight_bridges',
      trailer: apiPrefix + '/trailers',
      weightOperationsLog: apiPrefix + '/weight_bridges_log',
      userInformationTask: apiPrefix + '/user_information_task',
      vehicle: apiPrefix + '/vehicle',
      setTrueFuelControl: apiPrefix + '/vehicle/true_fuel_control',
      getVehicleSensors: apiPrefix + '/vehicle/sensors',
      setVehicleSensor: apiPrefix + '/vehicle/sensors',
      setVehicleMultiplier: apiPrefix + '/vehicle/multiplier',
      reportByObjects: apiPrefix + '/report_by_objects',
      reportByObjectsIncome: apiPrefix + '/report_by_objects_income',
      reportByVehicleIncome: apiPrefix + '/report_by_vehicles_income',
      reportFuelMovingInternal: apiPrefix + '/report_fuel_moving_internal',
      reportWeightingByObjects: apiPrefix + '/report_weighting_by_objects',
      reportWeightingByRfid: apiPrefix + '/report_weighting_by_rfid',
      reportDetailedRfid: apiPrefix + '/report_detailed_rfid',
      reportDetailedStorehouse: apiPrefix + '/report_detailed_storehouse',
      reportByRfid: apiPrefix + '/report_by_rfid',
      employee: apiPrefix + '/employee',
      partner: apiPrefix + '/partner',
      partnerTypes: apiPrefix + '/partner/type',
      tank: apiPrefix + '/tank',
      node: apiPrefix + '/node',
      setNodeVisible: apiPrefix + '/node/set_visible',
      getNodeTypes: apiPrefix + '/node/types',
      getCounterTypes: apiPrefix + '/node/counter_types',
      getNodeLevelObjects: apiPrefix + '/node/level_objects',
      tankLog: apiPrefix + '/tank/log',
      setVisible: apiPrefix + '/tank/set_visible',
      moveFuel: apiPrefix + '/tank/move_fuel',
      tankLevels: apiPrefix + '/tank/levels',
      storehouse: apiPrefix + '/storehouse',
      setSensorExist: apiPrefix + '/storehouse/sensor_exist',
      setTrueControl: apiPrefix + '/storehouse/true_control',
      income: apiPrefix + '/income',
      tankIncomeLog: apiPrefix + '/income/tank_income_log',
      setTankLog: apiPrefix + '/income/set_tank_log',
      apiServer: apiPrefix + '/api_server',
      getApiServerTypes: apiPrefix + '/api_server/types',
      testConnection: apiPrefix + '/api_server/test_connection',
      getObjectsByServerId: apiPrefix + '/api_server/objects',
      getObjectsRfidByServerId: apiPrefix + '/api_server/rfid',
      synchronizeObjects: apiPrefix + '/api_server/synchronize_objects',
      synchronizeRfidObjects: apiPrefix + '/api_server/synchronize_rfid_objects',
      setServerActive: apiPrefix + '/api_server/set_active',
      user: apiPrefix + '/user',
      getUserRoles: apiPrefix + '/user/roles',
      getUsersByCurrentCompany: apiPrefix + '/get_users_by_current_company',
      getMessages: apiPrefix + '/user_chat/:userId',
      userMessages: apiPrefix + '/user_chat',
      fuelMoving: apiPrefix + '/fuel_moving',
      calibration: apiPrefix + '/calibration',
      camera: apiPrefix + '/camera',
      cameraData: apiPrefix + '/camera/data',
      cameraDataLast: apiPrefix + '/camera/data/last',
      calibrationTable: apiPrefix + '/calibration/table',
      calibrationLogPhoto: apiPrefix + '/calibration/photo',
      productOperation: apiPrefix + '/product_operation',
      productOperationIncome: apiPrefix + '/product_operation/income',
      productOperationMoving: apiPrefix + '/product_operation/moving',
      productOperationInventory: apiPrefix + '/inventory',
      productOperationInventoryStatus: apiPrefix + '/inventory/status',
      productOperationInventoryBalance: apiPrefix + '/inventory/balance',

    })
})();
